import type { InputState } from './types';
type Action=keyof Pick<InputState,'forward'|'back'|'left'|'right'|'jump'|'dash'|'boost'|'fire'>;
type Point={x:number;y:number};
type Cb={setAction:(a:Action,d:boolean)=>void;addLook:(y:number,p:number)=>void;setScoreboard:(d:boolean)=>void};
export type MobileControlHandle={destroy:()=>void;reset:()=>void};
const LOOK=.0045;
export const isTouchDevice=()=>typeof window!=='undefined'&&(navigator.maxTouchPoints>0||'ontouchstart'in window);
const hold=(label:string,cls:string)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.className=`mobile-control ${cls}`;b.setAttribute('aria-label',label);return b;};
export function attachMobileControls(canvas:HTMLCanvasElement,cb:Cb):MobileControlHandle{
 const host=canvas.parentElement||document.body,layer=document.createElement('div');layer.className='mobile-controls';layer.innerHTML='<div class="mobile-look-zone"></div><div class="mobile-joystick"><div class="mobile-joystick-knob"></div></div><div class="mobile-action-cluster"></div><button type="button" class="mobile-control mobile-scoreboard" aria-label="Scoreboard">TAB</button><div class="mobile-orientation-warning"><div><b>ROTATE DEVICE</b><br><span>Landscape is recommended.</span></div></div>';host.appendChild(layer);
 const cluster=layer.querySelector('.mobile-action-cluster') as HTMLElement,knob=layer.querySelector('.mobile-joystick-knob') as HTMLElement,score=layer.querySelector('.mobile-scoreboard') as HTMLButtonElement;
 const buttons=[hold('FIRE','mobile-action-fire'),hold('JUMP','mobile-action-jump'),hold('DASH','mobile-action-dash'),hold('BOOST','mobile-action-boost')],acts:Action[]=['fire','jump','dash','boost'];buttons.forEach(b=>cluster.appendChild(b));
 const binds=buttons.map((b,i)=>{const a=acts[i],down=(e:PointerEvent)=>{if(e.pointerType!=='touch')return;e.preventDefault();b.dataset.active='true';try{b.setPointerCapture(e.pointerId);}catch{}cb.setAction(a,true);},up=(e:PointerEvent)=>{if(e.pointerType!=='touch')return;e.preventDefault();b.dataset.active='false';cb.setAction(a,false);};b.addEventListener('pointerdown',down,{passive:false});b.addEventListener('pointerup',up,{passive:false});b.addEventListener('pointercancel',up,{passive:false});b.addEventListener('lostpointercapture',up,{passive:false});return()=>{b.removeEventListener('pointerdown',down);b.removeEventListener('pointerup',up);b.removeEventListener('pointercancel',up);b.removeEventListener('lostpointercapture',up);};});
 const scoreDown=(e:PointerEvent)=>{if(e.pointerType==='touch'){e.preventDefault();score.dataset.active='true';cb.setScoreboard(true);}},scoreUp=(e:PointerEvent)=>{if(e.pointerType==='touch'){e.preventDefault();score.dataset.active='false';cb.setScoreboard(false);}};score.addEventListener('pointerdown',scoreDown,{passive:false});score.addEventListener('pointerup',scoreUp,{passive:false});score.addEventListener('pointercancel',scoreUp,{passive:false});
 const pts=new Map<number,Point>();let look:number|null=null,stick:number|null=null,origin:Point|null=null;
 const reset=()=>{pts.clear();look=null;stick=null;origin=null;knob.style.transform='translate(0,0)';(['forward','back','left','right','jump','dash','boost','fire'] as Action[]).forEach(a=>cb.setAction(a,false));cb.setScoreboard(false);buttons.forEach(b=>b.dataset.active='false');score.dataset.active='false';};
 const down=(e:PointerEvent)=>{if(e.pointerType!=='touch')return;e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.clientX<innerWidth*.42&&stick===null){stick=e.pointerId;origin={x:e.clientX,y:e.clientY};return;}if(look===null)look=e.pointerId;};
 const move=(e:PointerEvent)=>{if(e.pointerType!=='touch')return;const p=pts.get(e.pointerId);if(!p)return;e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.pointerId===look){cb.addLook((e.clientX-p.x)*LOOK,(e.clientY-p.y)*LOOK);return;}if(e.pointerId===stick&&origin){const dx=e.clientX-origin.x,dy=e.clientY-origin.y,r=62,nx=Math.max(-1,Math.min(1,dx/r)),ny=Math.max(-1,Math.min(1,dy/r));cb.setAction('left',nx<-.2);cb.setAction('right',nx>.2);cb.setAction('forward',ny<-.2);cb.setAction('back',ny>.2);const m=Math.min(1,Math.hypot(dx,dy)/r),a=Math.atan2(dy,dx);knob.style.transform=`translate(${Math.cos(a)*m*32}px,${Math.sin(a)*m*32}px)`;}};
 const up=(e:PointerEvent)=>{if(e.pointerType!=='touch')return;pts.delete(e.pointerId);if(e.pointerId===stick){stick=null;origin=null;(['forward','back','left','right'] as Action[]).forEach(a=>cb.setAction(a,false));knob.style.transform='translate(0,0)';}if(e.pointerId===look)look=null;};
 const vis=()=>{if(document.hidden)reset();};canvas.addEventListener('pointerdown',down,{passive:false});canvas.addEventListener('pointermove',move,{passive:false});canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('lostpointercapture',up);window.addEventListener('blur',reset);document.addEventListener('visibilitychange',vis);
 return{reset,destroy:()=>{reset();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('lostpointercapture',up);window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',vis);binds.forEach(f=>f());score.removeEventListener('pointerdown',scoreDown);score.removeEventListener('pointerup',scoreUp);score.removeEventListener('pointercancel',scoreUp);layer.remove();}};
}
